stages:
  - build_and_publish
  - notify_error  # Send message to Telegram if error

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

variables:
  # Включение отладки CICD
  CI_DEBUG_TRACE: "${CI_DEBUG_TRACE}"
  CI_DEBUG_SERVICES: "${CI_DEBUG_SERVICES}"
  # Оптимизация docker сборки
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1

build_and_publish:
  stage: build_and_publish
  tags: ["gp-docker"]
  image: node:18
  script:
    # Увеличение версии
    # - npm version patch --no-git-tag-version
    # - git add package.json
    # - git commit -m "chore: bump version to $(cat package.json | jq -r .version)"
    # - git push origin $CI_COMMIT_BRANCH
    - cat "$NPMRC2" > .npmrc
    - cat .npmrc
    # Сборка проекта
    - yarn install
    - yarn build
    # Публикация пакета
    - yarn add npm --dev
    - yarn run npm publish
  only:
    - main


notify_error_job:
  stage: notify_error
  script:
    - sh telegram-notifications.sh ❌
  when: on_failure #deploy fail
